apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctse-app
  name: ctse-app
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ctse-app
status:
  loadBalancer: {}